/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
//???

double*
add_1_svc(operands* argp, struct svc_req* rqstp) {
	static double result;

	/*
	 * insert server code here
	 */
	result = argp->a + argp->b;

	return &result;
}

double*
subtract_1_svc(operands* argp, struct svc_req* rqstp) {
	static double result;

	/*
	 * insert server code here
	 */
	result = argp->a - argp->b;

	return &result;
}

double*
multiply_1_svc(operands* argp, struct svc_req* rqstp) {
	static double result;

	/*
	 * insert server code here
	 */
	result = argp->a * argp->b;

	return &result;
}

double*
divide_1_svc(operands* argp, struct svc_req* rqstp) {
	static double result;

	/*
	 * insert server code here
	 */
	result = argp->a / argp->b;

	return &result;
}
