/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	double a;
	double b;
};
typedef struct operands operands;

#define CALCULATOR_PROG 0x20000001
#define CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  double * add_1(operands *, CLIENT *);
extern  double * add_1_svc(operands *, struct svc_req *);
#define SUBTRACT 2
extern  double * subtract_1(operands *, CLIENT *);
extern  double * subtract_1_svc(operands *, struct svc_req *);
#define MULTIPLY 3
extern  double * multiply_1(operands *, CLIENT *);
extern  double * multiply_1_svc(operands *, struct svc_req *);
#define DIVIDE 4
extern  double * divide_1(operands *, CLIENT *);
extern  double * divide_1_svc(operands *, struct svc_req *);
extern int calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  double * add_1();
extern  double * add_1_svc();
#define SUBTRACT 2
extern  double * subtract_1();
extern  double * subtract_1_svc();
#define MULTIPLY 3
extern  double * multiply_1();
extern  double * multiply_1_svc();
#define DIVIDE 4
extern  double * divide_1();
extern  double * divide_1_svc();
extern int calculator_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
