/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIME_SERVICE_H_RPCGEN
#define _TIME_SERVICE_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

enum ProcID {
	GET_TIME = 1,
	SET_TIME = 2,
};
typedef enum ProcID ProcID;

#define TIMESERVICE_PROG 0x20000001
#define TIMESERVICE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_time GET_TIME
extern char** get_time_1(void*, CLIENT*);
extern char** get_time_1_svc(void*, struct svc_req*);
#define set_time SET_TIME
extern void* set_time_1(char**, CLIENT*);
extern void* set_time_1_svc(char**, struct svc_req*);
extern int timeservice_prog_1_freeresult(SVCXPRT*, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_time GET_TIME
extern char** get_time_1();
extern char** get_time_1_svc();
#define set_time SET_TIME
extern void* set_time_1();
extern void* set_time_1_svc();
extern int timeservice_prog_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern bool_t xdr_ProcID(XDR*, ProcID*);

#else /* K&R C */
extern bool_t xdr_ProcID();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIME_SERVICE_H_RPCGEN */
