/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "time_service.h"

bool_t
xdr_ProcID (XDR *xdrs, ProcID *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}
